### ISSUE TITLE
It is posible to compile on arduino ide

### ISSUE THREAD

**Issue by TeguhTeknisi** [5VLogic/l_meter#1]
Hi 5VLogic,
Thanks for the video and the code.

Btw, i have build inductance meter, but the reading its not stable, i have using this code https://github.com/tetoblivion/Arduino-Inductance-Meter-with-Internal-Comparator

So, I want to make inductance meter using your code

It is posible to compile it on arduino ide?

i have try to copy the main.c code to arduino ide and got this error

>  Arduino_Pro_Mini_Inductance_Meter:41:11: error: '::main' must return 'int'
>  void main()
>            ^
> Arduino_Pro_Mini_Inductance_Meter:41:11: error: '::main' must return 'int'
>  void main()
>            ^
> exit status 1
> '::main' must return 'int'

Best Regrads
Teguh Teknisi

**Comment by 5VLogic** [comment]
Hi Teguh,

I'm glad you liked the video.

There shouldn't be any problems using the Arduino IDE, provided that a few modifications are made.
I'm guessing you directly pasted the whole contents in the sketch (?)
If so, you should just copy the contents of the `main()` and put them in the appropriate `setup()` and `loop()`
functions.
The reason is that there already is a `main()` created by the IDE that's hidden and that calls the `setup()` and `loop()`.
So this means that you're creating a second `main()` and I presume the compiler wants it to return something else 
than `void` which is likely the return type of the _real_ `void main()`.

I recommend putting everything in the first part from my `main()` into your `setup()` , and copy-paste everything in the
`while(1)` into `loop()`. Remove `main()`. Obviously also copy-paste the variables, definitions, includes and other functions.

Hopefully this helps!

**Comment by TeguhTeknisi** [comment]
> Hi Teguh,
> 
> I'm glad you liked the video.
> 
> There shouldn't be any problems using the Arduino IDE, provided that a few modifications are made. I'm guessing you directly pasted the whole contents in the sketch (?) If so, you should just copy the contents of the `main()` and put them in the appropriate `setup()` and `loop()` functions. The reason is that there already is a `main()` created by the IDE that's hidden and that calls the `setup()` and `loop()`. So this means that you're creating a second `main()` and I presume the compiler wants it to return something else than `void` which is likely the return type of the _real_ `void main()`.
> 

Yes, that's what i did.

> I recommend putting everything in the first part from my `main()` into your `setup()` , and copy-paste everything in the `while(1)` into `loop()`. Remove `main()`. Obviously also copy-paste the variables, definitions, includes and other functions.
> 
> Hopefully this helps!

So that how to convert to arduino ide.
its compiled now and i can add oled ssd1306 to it.

Thanks a lot for the help.

Best Regrads,
Teguh Teknisi
